Add check to fail if dependency checker found a vuln

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,12 +14,13 @@ before_install:
  - chmod 777 data report
  - docker pull owasp/dependency-check
  - docker run --volume $PWD:/src --volume $PWD/data:/usr/share/dependency-check/data --volume $PWD/report:/report owasp/dependency-check --scan /src --format "ALL" --project "Cryptopus OWASP Dependency Check" --out /report
+ - ls report/
  - |
    grep '"vulnerableCount">0<' report/dependency-check-report.html
-    if [[ $? -ne 0 ]]; then
-      echo "ERROR! Vulnerability found by OWASP Dependency Checker. Build aborted. See above."
-      exit 1
-    fi
+   if [[ $? -ne 0 ]]; then
+     echo "ERROR! Vulnerability found by OWASP Dependency Checker. Build aborted. See above."
+     exit 1
+   fi
  - sudo service mysql restart
 install:
  - bundle install --path vendor/bundle
